# Generated by Django 5.0.1 on 2024-02-04 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cashAmount', models.IntegerField(blank=True, null=True)),
                ('gifts', models.CharField(blank=True, max_length=8, null=True)),
                ('createdQr', models.ImageField(default=None, upload_to='media/createdQr/')),
                ('createdFor', models.CharField(choices=[('Retailer', 'Retailer'), ('Electrician', 'Electrician')], default='Retailer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfi_image', models.ImageField(upload_to='media/selfi_images/')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('adhar', models.CharField(max_length=20, unique=True)),
                ('pan', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('doa_marriage', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gst', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('doa_marriage', models.DateField(blank=True, null=True)),
                ('firm_image', models.ImageField(upload_to='media/firm_images/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usedQrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashAmount', models.IntegerField()),
                ('gifts', models.CharField(max_length=150)),
                ('usedQr', models.ImageField(default=None, upload_to='media/usedQr/')),
                ('createdFor', models.CharField(max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('usedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifts', models.CharField(default='Empty', max_length=120)),
                ('cash_coins', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
