# Generated by Django 5.0.1 on 2024-02-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedqrcode',
            name='cashAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
