# Generated by Django 5.0.1 on 2024-02-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_managermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managermodel',
            old_name='user',
            new_name='manager',
        ),
    ]
